<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      //新期约实例不同于 then()或 catch()方式返回的实例。因为 onFinally 被设计为一个状态无关的方法，所以在大多数情况下它将表现为父期约的传递
      //对于已解决状态和被拒绝状态都是如此。
      let p1 = Promise.resolve("foo");
      // 这里都会原样后传
      let p2 = p1.finally();
      let p3 = p1.finally(() => undefined);
      let p4 = p1.finally(() => {});
      let p5 = p1.finally(() => Promise.resolve());
      let p6 = p1.finally(() => "bar");
      let p7 = p1.finally(() => Promise.resolve("bar"));
      let p8 = p1.finally(() => Error("qux"));
      setTimeout(console.log, 0, p2); // Promise <resolved>: foo
      setTimeout(console.log, 0, p3); // Promise <resolved>: foo
      setTimeout(console.log, 0, p4); // Promise <resolved>: foo
      setTimeout(console.log, 0, p5); // Promise <resolved>: foo
      setTimeout(console.log, 0, p6); // Promise <resolved>: foo
      setTimeout(console.log, 0, p7); // Promise <resolved>: foo
      setTimeout(console.log, 0, p8); // Promise <resolved>: foo

      //如果返回的是一个待定的期约，或者 onFinally 处理程序抛出了错误（显式抛出或返回了一个拒绝期约），则会返回相应的期约（待定或拒绝）
      // Promise.resolve()保留返回的期约
      let p9 = p1.finally(() => new Promise(() => {}));
      let p10 = p1.finally(() => Promise.reject());
      // Uncaught (in promise): undefined
      setTimeout(console.log, 0, p9); // Promise <pending>
      setTimeout(console.log, 0, p10); // Promise <rejected>: undefined
      let p11 = p1.finally(() => {
        throw "baz";
      });
      // Uncaught (in promise) baz
      setTimeout(console.log, 0, p11); // Promise <rejected>: baz
    </script>
  </body>
</html>
